#!/bin/bash
#
# Copyright 2018 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# make us exit on a failure
set -e

# This test uses previously prepared dex and jar files. They need to
# be re-packaged to match the files that the run-test-jar script
# expects.
if [[ $@ != *"--jvm"* ]]; then
  zip ${TEST_NAME}.jar classes.dex
else
  unzip -d classes classes.jar
fi
