#!/bin/bash
#
# Copyright (C) 2012 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Stop if something fails.
set -e

export ORIGINAL_JAVAC="$JAVAC"

# Wrapper function for javac which invokes the compiler and applies
# additional setup steps for the test.
function javac_wrapper {
  set -e # Stop on error - the caller script may not have this set.

  $ORIGINAL_JAVAC "$@"

  # Classes available at compile time, but not at runtime.
  rm -f classes/android/test/anno/MissingAnnotation.class
  rm -f 'classes/android/test/anno/ClassWithInnerAnnotationClass$MissingInnerAnnotationClass.class'

  # overwrite RenamedEnum in classes
  if [ -f classes2/android/test/anno/RenamedEnumClass.java ] ; then
    mv classes2/android/test/anno/RenamedEnumClass.java classes/android/test/anno/RenamedEnumClass.java
  fi
}

export -f javac_wrapper
export JAVAC=javac_wrapper

######################################################################

./default-build "$@"
