#!/bin/bash
#
# Copyright 2019 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# make us exit on a failure
set -e

count=5000

# Generate the other class.
other_file="src-art/Other.java"
cat >${other_file} <<EOF
class Other {
static String getString(int i) {
switch(i) {
EOF

for i in $(seq 1 "$count"); do
  echo "  case ${i}: return \"string$i\";" >> "${other_file}"
done

cat >>${other_file} <<EOF
}
return "not found";
}
}
EOF

./default-build "$@"
