#!/bin/bash
#
# Copyright 2017 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# On RI we need to turn class-load tests off since those events are buggy around
# pop-frame (see b/116003018).
ARGS=""
if [[ "$TEST_RUNTIME" == "jvm" ]]; then
  ARGS="--args DISABLE_CLASS_LOAD_TESTS"
fi

# The jitthreshold prevents the jit from compiling anything except those which
# we explicitly request.
./default-run "$@" --android-runtime-option -Xjitthreshold:1000 --jvmti $ARGS
